CREATE TABLE IF NOT EXISTS produto (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    estoque BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS movimentacao (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tipo ENUM('ENTRADA', 'SAIDA') NOT NULL,
    quantidade BIGINT NOT NULL,
    data DATETIME NOT NULL,
    produto_id BIGINT NOT NULL,
    FOREIGN KEY (produto_id) REFERENCES produto(id)
);

INSERT INTO produto (id, nome, estoque) VALUES
(1, 'Teclado', 22),
(2, 'Mouse', 33),
(3, 'Monitor', 19),
(4, 'Notebook', 6),
(5, 'Cabo HDMI', 79),
(6, 'Webcam', 9),
(7, 'Headset', 24),
(8, 'Impressora', 6),
(9, 'HD Externo', 15),
(10, 'Pen Drive 32GB', 79);

INSERT INTO movimentacao (id, tipo, quantidade, data, produto_id) VALUES
( 1, 'ENTRADA', 10, CURRENT_TIMESTAMP - INTERVAL 10 DAY, 1),
( 2, 'ENTRADA', 25, CURRENT_TIMESTAMP - INTERVAL 12 DAY, 2),
( 3, 'ENTRADA', 15, CURRENT_TIMESTAMP - INTERVAL 14 DAY, 3),
( 4, 'ENTRADA', 5, CURRENT_TIMESTAMP - INTERVAL 16 DAY, 4),
( 5, 'ENTRADA', 50, CURRENT_TIMESTAMP - INTERVAL 18 DAY, 5),
( 6, 'ENTRADA', 12, CURRENT_TIMESTAMP - INTERVAL 20 DAY, 6),
( 7, 'ENTRADA', 30, CURRENT_TIMESTAMP - INTERVAL 22 DAY, 7),
( 8, 'ENTRADA', 7, CURRENT_TIMESTAMP - INTERVAL 24 DAY, 8),
( 9, 'ENTRADA', 20, CURRENT_TIMESTAMP - INTERVAL 26 DAY, 9),
(10, 'ENTRADA', 100, CURRENT_TIMESTAMP - INTERVAL 28 DAY, 10),
(11, 'ENTRADA', 5, CURRENT_TIMESTAMP - INTERVAL 5 DAY, 1),
(12, 'ENTRADA', 10, CURRENT_TIMESTAMP - INTERVAL 4 DAY, 2),
(13, 'ENTRADA', 8, CURRENT_TIMESTAMP - INTERVAL 3 DAY, 3),
(14, 'ENTRADA', 2, CURRENT_TIMESTAMP - INTERVAL 2 DAY, 4),
(15, 'ENTRADA', 20, CURRENT_TIMESTAMP - INTERVAL 1 DAY, 5);

INSERT INTO movimentacao (id, tipo, quantidade, data, produto_id) VALUES
(16, 'SAIDA', 2, CURRENT_TIMESTAMP - INTERVAL 9 DAY, 1),
(17, 'SAIDA', 5, CURRENT_TIMESTAMP - INTERVAL 11 DAY, 1),
(18, 'SAIDA', 3, CURRENT_TIMESTAMP - INTERVAL 13 DAY, 3),
(19, 'SAIDA', 1, CURRENT_TIMESTAMP - INTERVAL 15 DAY, 4),
(20, 'SAIDA', 10, CURRENT_TIMESTAMP - INTERVAL 17 DAY, 5),
(21, 'SAIDA', 3, CURRENT_TIMESTAMP - INTERVAL 19 DAY, 6),
(22, 'SAIDA', 4, CURRENT_TIMESTAMP - INTERVAL 21 DAY, 7),
(23, 'SAIDA', 1, CURRENT_TIMESTAMP - INTERVAL 23 DAY, 8),
(24, 'SAIDA', 5, CURRENT_TIMESTAMP - INTERVAL 25 DAY, 9),
(25, 'SAIDA', 20, CURRENT_TIMESTAMP - INTERVAL 27 DAY, 10),
(26, 'SAIDA', 1, CURRENT_TIMESTAMP - INTERVAL 6 DAY, 1),
(27, 'SAIDA', 2, CURRENT_TIMESTAMP - INTERVAL 5 DAY, 1),
(28, 'SAIDA', 1, CURRENT_TIMESTAMP - INTERVAL 4 DAY, 1),
(29, 'SAIDA', 1, CURRENT_TIMESTAMP - INTERVAL 3 DAY, 5),
(30, 'SAIDA', 2, CURRENT_TIMESTAMP - INTERVAL 2 DAY, 7),
(31, 'SAIDA', 1, CURRENT_TIMESTAMP - INTERVAL 1 DAY, 10);